spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
logging:
  level:
    com.tao.learn.mybatisplug.quickstart.mapper: debug
mybatis-plus:
  type-enums-package: com.tao.learn.mybatisplug.quickstart.enums