server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: gateway-group-3
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/data?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gateway:
      routes:
        - id: demo
          uri: http://127.0.0.1:8091
          order: 10
          predicates:
            - Path=/api/test1/**,/api/test2/demo1,/api/test3/**
#            - Path=/api/test1/**
#            - Path=/api/test2/demo1
#            - Path=/api/test3/**
          filters:
            - StripPrefix=1   # 去除/api的前缀
        - id: jd
          uri: http://www.jd.com:80
          order: 5
          predicates:
            - Path=/api/jd
          filters:
            - StripPrefix=1

